CUDA_AVAILABLE_DEVICES=0 python dice_coefficient_from_kfold_transunet.py --model_path models/transunet_final_project/transunet_final_project_0_final.pth --kfold 0
CUDA_AVAILABLE_DEVICES=0 python dice_coefficient_from_kfold_transunet.py --model_path models/transunet_final_project/transunet_final_project_1_final.pth --kfold 1
CUDA_AVAILABLE_DEVICES=0 python dice_coefficient_from_kfold_transunet.py --model_path models/transunet_final_project/transunet_final_project_2_final.pth --kfold 2
CUDA_AVAILABLE_DEVICES=0 python dice_coefficient_from_kfold_transunet.py --model_path models/transunet_final_project/transunet_final_project_3_final.pth --kfold 3
CUDA_AVAILABLE_DEVICES=0 python dice_coefficient_from_kfold_transunet.py --model_path models/transunet_final_project/transunet_final_project_4_final.pth --kfold 4

CUDA_AVAILABLE_DEVICES=0 python dice_coefficient_from_kfold.py --model_path models/unet_final_project_vanilla_logits/unet_final_project_vanilla_logits_0_99.pth --kfold 0
CUDA_AVAILABLE_DEVICES=0 python dice_coefficient_from_kfold.py --model_path models/unet_final_project_vanilla_logits/unet_final_project_vanilla_logits_1_99.pth --kfold 1
CUDA_AVAILABLE_DEVICES=0 python dice_coefficient_from_kfold.py --model_path models/unet_final_project_vanilla_logits/unet_final_project_vanilla_logits_2_99.pth --kfold 2
CUDA_AVAILABLE_DEVICES=0 python dice_coefficient_from_kfold.py --model_path models/unet_final_project_vanilla_logits/unet_final_project_vanilla_logits_3_99.pth --kfold 3
CUDA_AVAILABLE_DEVICES=0 python dice_coefficient_from_kfold.py --model_path models/unet_final_project_vanilla_logits/unet_final_project_vanilla_logits_4_99.pth --kfold 4

CUDA_AVAILABLE_DEVICES=0 python dice_coefficient_from_kfold.py --model_path models/unet_final_project_vanilla_pretrained_deeplab_with_cross_entropy/unet_final_project_vanilla_pretrained_deeplab_with_cross_entropy_0_final.pth --kfold 0
CUDA_AVAILABLE_DEVICES=0 python dice_coefficient_from_kfold.py --model_path models/unet_final_project_vanilla_pretrained_deeplab_with_cross_entropy/unet_final_project_vanilla_pretrained_deeplab_with_cross_entropy_1_final.pth --kfold 1
CUDA_AVAILABLE_DEVICES=0 python dice_coefficient_from_kfold.py --model_path models/unet_final_project_vanilla_pretrained_deeplab_with_cross_entropy/unet_final_project_vanilla_pretrained_deeplab_with_cross_entropy_2_final.pth --kfold 2
CUDA_AVAILABLE_DEVICES=0 python dice_coefficient_from_kfold.py --model_path models/unet_final_project_vanilla_pretrained_deeplab_with_cross_entropy/unet_final_project_vanilla_pretrained_deeplab_with_cross_entropy_3_final.pth --kfold 3
CUDA_AVAILABLE_DEVICES=0 python dice_coefficient_from_kfold.py --model_path models/unet_final_project_vanilla_pretrained_deeplab_with_cross_entropy/unet_final_project_vanilla_pretrained_deeplab_with_cross_entropy_4_final.pth --kfold 4
